import { Clerk } from "https://esm.sh/@clerk/clerk-js@6?bundle";

const DEVELOPMENT = location.protocol === "http:";
const API_ORIGIN = DEVELOPMENT ? `http://${location.hostname}:8787` : "https://parallel-vision-anam-token.parallelvision.workers.dev";
const CLERK = DEVELOPMENT ? { key:"pk_test_Y2xpbWJpbmctd29tYmF0LTI3MTcuY2xlcmsuYWNjb3VudHMuZGV2JA", domain:"climbing-wombat-2717.clerk.accounts.dev" } : { key:"pk_live_Y2xlcmsucGFyYWxsZWx2aXNpb25sYWJlbC5jb20k", domain:"clerk.parallelvisionlabel.com" };
const $ = id => document.getElementById(id);
const elements = { identity:$("accountIdentity"), content:$("accountContent"), signIn:$("accountSignIn"), signOut:$("accountSignOut"), profileForm:$("profileForm"), name:$("preferredName"), profileLanguage:$("profileLanguage"), profileStatus:$("profileStatus"), balance:$("accountBalance"), credits:$("creditHistory"), billing:$("billingHistory"), newsletterForm:$("newsletterForm"), newsletter:$("newsletterUpdates"), nina:$("ninaTransmissions"), newsletterStatus:$("newsletterStatus"), forget:$("forgetMemory"), confirm:$("memoryConfirm"), cancel:$("memoryCancel"), delete:$("memoryDelete"), memoryStatus:$("memoryStatus"), language:$("accountLanguage") };
let clerk;
let language = localStorage.getItem("pvLanguage") === "de" ? "de" : "en";
const copy = {
  en:{accountTitle:"Account",accountIntro:"Account settings, Signal Credits and Nina continuity.",signIn:"Sign in",profile:"Profile",profileCopy:"Explicit profile data is separate from Nina’s conversational memory.",preferredName:"Preferred name",language:"Language",saveProfile:"Save profile",credits:"Signal Credits",balance:"Current balance",getCredits:"Get Signal Credits",billing:"Billing",billingCopy:"Signal Credit purchase records associated with this account.",pack:"Pack",amount:"Amount",status:"Status",date:"Date",memory:"Memory",memoryCopy:"Nina remembers relevant conversations to create continuity over time.",forgetMemory:"Forget Nina’s memory",newsletter:"Newsletter",newsletterCopy:"Preferences are stored now. Email delivery infrastructure is not connected yet.",pvUpdates:"Parallel Vision updates",ninaUpdates:"Nina transmissions",savePreferences:"Save preferences",signOut:"Sign out",confirmTitle:"Forget Nina’s memory?",confirmCopy:"This permanently deletes Nina’s stored conversational and relationship memory for this account. Your profile, Signal Credits, purchases and Clerk account remain.",cancel:"Cancel",confirmDelete:"Delete Nina’s memory"},
  de:{accountTitle:"Konto",accountIntro:"Kontoeinstellungen, Signal Credits und Ninas Kontinuität.",signIn:"Anmelden",profile:"Profil",profileCopy:"Explizite Profildaten sind von Ninas Gesprächserinnerung getrennt.",preferredName:"Bevorzugter Name",language:"Sprache",saveProfile:"Profil speichern",credits:"Signal Credits",balance:"Aktueller Stand",getCredits:"Signal Credits kaufen",billing:"Zahlungen",billingCopy:"Signal-Credit-Käufe, die diesem Konto zugeordnet sind.",pack:"Paket",amount:"Betrag",status:"Status",date:"Datum",memory:"Erinnerung",memoryCopy:"Nina erinnert sich an relevante Gespräche, um über Zeit Kontinuität zu schaffen.",forgetMemory:"Ninas Erinnerung löschen",newsletter:"Newsletter",newsletterCopy:"Die Präferenzen werden gespeichert. Der E-Mail-Versand ist noch nicht verbunden.",pvUpdates:"Parallel Vision Updates",ninaUpdates:"Nina Übertragungen",savePreferences:"Präferenzen speichern",signOut:"Abmelden",confirmTitle:"Ninas Erinnerung löschen?",confirmCopy:"Dies löscht dauerhaft Ninas gespeicherte Gesprächs- und Beziehungserinnerung für dieses Konto. Profil, Signal Credits, Käufe und Clerk-Konto bleiben bestehen.",cancel:"Abbrechen",confirmDelete:"Ninas Erinnerung löschen"}
};

function applyLanguage(){document.documentElement.lang=language;document.querySelectorAll("[data-copy]").forEach(el=>{const value=copy[language][el.dataset.copy];if(value)el.textContent=value});document.querySelectorAll("[data-language]").forEach(el=>el.classList.toggle("is-active",el.dataset.language===language));localStorage.setItem("pvLanguage",language)}
async function loadClerkUI(){if(window.__internal_ClerkUICtor)return window.__internal_ClerkUICtor;await new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=`https://${CLERK.domain}/npm/@clerk/ui@1/dist/ui.browser.js`;script.onload=resolve;script.onerror=reject;document.head.appendChild(script)});return window.__internal_ClerkUICtor}
async function authHeaders(){const token=await clerk?.session?.getToken?.();return token?{"Authorization":`Bearer ${token}`,"Content-Type":"application/json","Accept":"application/json"}:{"Content-Type":"application/json"}}
async function api(path,options={}){const response=await fetch(`${API_ORIGIN}${path}`,{cache:"no-store",...options,headers:{...(await authHeaders()),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Request failed");return data}
const money=(amount,currency)=>new Intl.NumberFormat(language,{style:"currency",currency:currency||"EUR"}).format(amount);
const date=value=>value?new Intl.DateTimeFormat(language,{dateStyle:"medium"}).format(new Date(value)):"—";
function list(container,rows,renderer){container.innerHTML="";if(!rows.length){const p=document.createElement("p");p.className="account-list-empty";p.textContent=language==="de"?"Noch keine Einträge.":"No records yet.";container.append(p);return}rows.forEach(row=>{const item=document.createElement("div");item.className="account-list-row";renderer(item,row);container.append(item)})}
async function loadAccount(){const [account,credits,history,billing]=await Promise.all([api("/api/account"),api("/api/nina/credits"),api("/api/nina/credits/history?limit=8"),api("/api/account/billing?limit=12")]);elements.name.value=account.preferences.preferredName||account.displayName||"";elements.profileLanguage.value=account.preferences.language||language;elements.newsletter.checked=account.preferences.newsletterUpdates;elements.nina.checked=account.preferences.ninaTransmissions;elements.balance.textContent=Number(credits.balance).toLocaleString(language);list(elements.credits,history.transactions||[],(item,row)=>{item.innerHTML=`<strong>${row.amount>0?"+":""}${row.amount} credits</strong><span>${date(row.createdAt)}</span>`});list(elements.billing,billing.purchases||[],(item,row)=>{item.classList.add("account-billing-row");item.innerHTML=`<strong>${row.credits} credits</strong><span>${money(row.amount,row.currency)}</span><span>${row.status}</span><span>${date(row.paidAt||row.createdAt)}</span>`})}
function syncAuth(){const signedIn=Boolean(clerk?.isSignedIn&&clerk?.session);elements.content.hidden=!signedIn;elements.signIn.hidden=signedIn;elements.identity.textContent=signedIn?(clerk.user?.fullName||clerk.user?.primaryEmailAddress?.emailAddress||"Parallel Vision account"):(language==="de"?"Melde dich an, um dein Konto zu öffnen.":"Sign in to open your account.");if(signedIn)loadAccount().catch(()=>{elements.identity.textContent=language==="de"?"Konto vorübergehend nicht verfügbar.":"Account temporarily unavailable."})}
function openConfirm(){elements.confirm.hidden=false;elements.confirm.setAttribute("aria-hidden","false");document.body.classList.add("account-modal-open");elements.cancel.focus()}
function closeConfirm(){elements.confirm.hidden=true;elements.confirm.setAttribute("aria-hidden","true");document.body.classList.remove("account-modal-open");elements.forget.focus()}
function clearLocalNinaMemory(){for(let index=localStorage.length-1;index>=0;index-=1){const key=localStorage.key(index);if(key?.startsWith("nina_fok_memory_v2:")||key==="nina_fok_alejandro_memory_v1")localStorage.removeItem(key)}}

elements.language.addEventListener("click",()=>{language=language==="de"?"en":"de";elements.profileLanguage.value=language;applyLanguage();if(!clerk?.isSignedIn)syncAuth()});
elements.signIn.addEventListener("click",()=>clerk?.openSignIn());
elements.signOut.addEventListener("click",async()=>{await clerk?.signOut();syncAuth()});
elements.profileForm.addEventListener("submit",async event=>{event.preventDefault();elements.profileStatus.textContent="Saving…";try{language=elements.profileLanguage.value==="de"?"de":"en";await api("/api/account/profile",{method:"PUT",body:JSON.stringify({preferredName:elements.name.value,language})});applyLanguage();elements.profileStatus.textContent=language==="de"?"Profil gespeichert.":"Profile saved."}catch{elements.profileStatus.textContent=language==="de"?"Profil konnte nicht gespeichert werden.":"Unable to save profile."}});
elements.newsletterForm.addEventListener("submit",async event=>{event.preventDefault();elements.newsletterStatus.textContent="Saving…";try{await api("/api/account/preferences",{method:"PUT",body:JSON.stringify({newsletterUpdates:elements.newsletter.checked,ninaTransmissions:elements.nina.checked})});elements.newsletterStatus.textContent=language==="de"?"Präferenzen gespeichert.":"Preferences saved."}catch{elements.newsletterStatus.textContent=language==="de"?"Speichern fehlgeschlagen.":"Unable to save preferences."}});
elements.forget.addEventListener("click",openConfirm);elements.cancel.addEventListener("click",closeConfirm);elements.confirm.addEventListener("click",event=>{if(event.target===elements.confirm)closeConfirm()});elements.delete.addEventListener("click",async()=>{elements.delete.disabled=true;try{await api("/memory",{method:"DELETE",body:"{}"});clearLocalNinaMemory();closeConfirm();elements.memoryStatus.textContent=language==="de"?"Ninas Erinnerung wurde gelöscht.":"Nina’s memory was deleted."}catch{elements.memoryStatus.textContent=language==="de"?"Erinnerung konnte nicht gelöscht werden.":"Unable to delete memory."}finally{elements.delete.disabled=false}});
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!elements.confirm.hidden)closeConfirm()});

applyLanguage();
try{const ClerkUI=await loadClerkUI();clerk=new Clerk(CLERK.key);await clerk.load({ui:{ClerkUI}});clerk.addListener?.(syncAuth);syncAuth()}catch{elements.identity.textContent=language==="de"?"Anmeldung ist vorübergehend nicht verfügbar.":"Sign-in is temporarily unavailable."}
