import test from 'node:test';
import assert from 'node:assert/strict';
import {trainingPreview,createDataset,characterPreview} from '../lab-worker/soul.mjs';
const photo=Uint8Array.from([...Buffer.from('RIFF'),0,0,0,0,...Buffer.from('WEBP'),1,2,3,4]);
function archive(){const b=new Uint8Array(38+photo.length),v=new DataView(b.buffer);v.setUint32(0,0x04034b50,true);v.setUint32(18,photo.length,true);v.setUint32(22,photo.length,true);v.setUint16(26,8,true);b.set(Buffer.from('0001.webp').subarray(0,8),30);b.set(photo,38);return b;}
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
test('first stored training photo is preserved exactly',()=>assert.deepEqual(trainingPreview(archive()),photo));
test('truncated, compressed, encrypted and oversized entries do not yield a portrait',()=>{assert.equal(trainingPreview(archive().slice(0,-1)),null);for(const [offset,value] of [[6,1],[8,8]]){const b=archive();new DataView(b.buffer).setUint16(offset,value,true);assert.equal(trainingPreview(b),null);}const b=archive();new DataView(b.buffer).setUint32(18,5*1024*1024,true);assert.equal(trainingPreview(b),null);});
test('dataset upload saves a private cover separately from its ZIP',async()=>{const saved=new Map();const env={LAB_MEDIA:{put:async(k,b)=>saved.set(k,b),delete:async k=>saved.delete(k)}};const d={first:async()=>({n:0}),limitedBody:async()=>archive(),run:async()=>{},now:()=>1,fail};const result=await createDataset(new Request('https://test',{method:'POST',headers:{'content-type':'application/zip','x-photo-count':'20'}}),env,'owner',d);assert.deepEqual(saved.get(`owner/soul/previews/${result.id}.webp`),photo);assert.ok(saved.has(`owner/soul/datasets/${result.id}.zip`));});
test('portrait lookup checks character ownership and does not read storage for a missing character',async()=>{let read=false;await assert.rejects(characterPreview({LAB_MEDIA:{get:async()=>{read=true;}}},'other','c1',{uid:x=>x,first:async(_e,_sql,id,owner)=>{assert.equal(owner,'other');return null;},fail}),e=>e.status===404);assert.equal(read,false);});
test('portrait is available without the temporary dataset record or ZIP',async()=>{const response=await characterPreview({LAB_MEDIA:{get:async key=>{assert.equal(key,'owner/soul/previews/d1.webp');return {body:photo};}}},'owner','c1',{uid:x=>x,first:async()=>({dataset_id:'d1'}),fail});assert.equal(response.headers.get('content-type'),'image/webp');assert.match(response.headers.get('cache-control'),/private/);assert.deepEqual(new Uint8Array(await response.arrayBuffer()),photo);});
