import assert from 'node:assert/strict';
import {readFile,writeFile,unlink} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import {imageModelParameters,buildImageModelInput,requestFlash} from '../lab-worker/image-models.mjs';
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
const input=engine=>({type:'image',engine,prompt:'Editorial photograph',resolution:'1k',aspectRatio:'16:9',mode:'image'});
const flash=imageModelParameters(input('flash'),{fail}),kling=imageModelParameters(input('kling'),{fail});
assert.equal(buildImageModelInput(flash,[]).n,1);
// Flash's endpoint does not advertise output_format. Do not send unsupported knobs.
assert.equal(Object.hasOwn(buildImageModelInput(flash,[]),'output_format'),false);
assert.equal(Object.hasOwn(buildImageModelInput(flash,['data:image/png;base64,AA==']),'output_format'),false);
await assert.rejects(requestFlash('secret-key',{},async()=>Response.json({error:{message:'Unsupported parameter: output_format'}},{status:400})),e=>e.definite===true&&e.message.includes('Unsupported parameter: output_format'));
await assert.rejects(requestFlash('secret-key',{},async()=>Response.json({error:{message:'Invalid secret-key Bearer sk-test123 https://private.test/a data:image/png;base64,AAAA'}},{status:400})),e=>!e.message.includes('secret-key')&&!e.message.includes('sk-test123')&&!e.message.includes('private.test')&&!e.message.includes('AAAA'));
await assert.rejects(requestFlash('test',{},async()=>new Response('gateway',{status:502})),e=>e.definite===true&&e.message.includes('HTTP 502'));
assert.equal(buildImageModelInput(flash,['data:image/png;base64,AA==']).input_references[0].image_url.url,'data:image/png;base64,AA==');
assert.equal(buildImageModelInput(kling,['https://test/image.png']).image_url,'https://test/image.png');
assert.throws(()=>buildImageModelInput(kling,['a','b']),/one base/);
assert.throws(()=>imageModelParameters({...input('kling'),resolution:'4k'},{fail}),/1K or 2K/);
assert.throws(()=>imageModelParameters({...input('kling'),prompt:'a'.repeat(2501)},{fail}),/2,500/);
await assert.rejects(requestFlash('test',{},async()=>{throw Error('network')}),e=>e.definite===false);
await assert.rejects(requestFlash('test',{},async()=>new Response('{}',{status:401})),e=>e.definite===true);
let redirectCalls=0;await assert.rejects(requestFlash('test',{},async(url,options)=>{redirectCalls++;assert.equal(options.redirect,'manual');return new Response(null,{status:307,headers:{location:'https://other.test'}})}),e=>e.definite===true);assert.equal(redirectCalls,1);
const temporary=new URL('../lab-worker/.image-models-test-worker.mjs',import.meta.url);
const source=(await readFile(new URL('../lab-worker/worker.mjs',import.meta.url),'utf8')).replace('const owner=await authenticate(request,env),path=url.pathname,method=request.method;',"const owner='test-owner',path=url.pathname,method=request.method;");
await writeFile(temporary,source+'\nexport {route,refreshJob};\n');
const originalFetch=globalThis.fetch;
try{
  const {route}=await import(temporary.href);
  const db=new DatabaseSync(':memory:');
  db.exec(await readFile(new URL('../lab-worker/schema.sql',import.meta.url),'utf8'));
  for(const file of ['0002-images.sql','0003-concurrency.sql'])db.exec(await readFile(new URL('../lab-worker/migrations/'+file,import.meta.url),'utf8'));
  const prepare=(sql,args=[])=>({bind(...values){return prepare(sql,values)},async first(){return db.prepare(sql).get(...args)},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:r.changes}}}});
  const storage=new Map(),env={OPENROUTER_API_KEY:'test-only',FAL_KEY:'test-only',LAB_DB:{prepare,batch:async list=>{db.exec('BEGIN');try{const values=[];for(const s of list)values.push(await s.run());db.exec('COMMIT');return values}catch(e){db.exec('ROLLBACK');throw e}}},LAB_MEDIA:{put:async(k,v)=>storage.set(k,v),delete:async k=>storage.delete(k),get:async k=>storage.has(k)?{json:async()=>JSON.parse(storage.get(k)),body:storage.get(k)}:null}};
  const call=(engine,extra={})=>route(new Request('https://lab.test/api/image-models/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({settings:input(engine),referenceSourceIds:[],...extra})}),env,{});
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
  let requests=[];
  globalThis.fetch=async(url,options)=>{requests.push({url,body:JSON.parse(options.body)});if(url==='https://openrouter.ai/api/v1/images')return Response.json({data:[{b64_json:png,media_type:'image/png'}],usage:{cost:0.018}});if(url.includes('queue.fal.run'))return Response.json({request_id:'test-kling-id'});throw Error('Unexpected network request: '+url)};
  let result=await (await call('flash')).json();assert.equal(result.job.status,'completed');assert.equal(result.job.settings.engine,'flash');assert.equal(requests.length,1);assert.equal(requests[0].body.aspect_ratio,'16:9');assert.ok(result.job.outputId);
  assert.equal(db.prepare('SELECT SUM(estimate_microusd) AS total FROM spend').get().total,18000);
  assert.equal(db.prepare('SELECT settled_cost FROM jobs WHERE id=?').get(result.job.id).settled_cost,0.018);
  result=await (await call('kling')).json();assert.equal(result.job.status,'queued');assert.equal(result.job.settings.model,'fal-ai/kling-image/v3/text-to-image');assert.equal(requests.at(-1).body.num_images,1);
  const n=requests.length;
  await assert.rejects(call('kling',{referenceSourceIds:[crypto.randomUUID(),crypto.randomUUID()]}),/1 to 1/);assert.equal(requests.length,n);
  const key=env.OPENROUTER_API_KEY;delete env.OPENROUTER_API_KEY;await assert.rejects(call('flash'),/OPENROUTER_API_KEY/);env.OPENROUTER_API_KEY=key;
  globalThis.fetch=async()=>{throw Error('timeout')};result=await (await call('flash')).json();assert.equal(result.job.status,'uncertain');
  await assert.rejects(call('flash'),/interrupted/);
  db.prepare("UPDATE jobs SET state='resolved' WHERE state='uncertain'").run();
  globalThis.fetch=async()=>new Response('{}',{status:401});const spend=db.prepare('SELECT SUM(estimate_microusd) AS total FROM spend').get().total;
  result=await (await call('flash')).json();assert.equal(result.job.status,'failed');assert.equal(db.prepare('SELECT SUM(estimate_microusd) AS total FROM spend').get().total,spend);
  db.prepare('INSERT INTO settings VALUES(?,?,?,?,?,?)').run('test-owner','',0,0,1000000,Date.now());
  db.prepare('INSERT INTO spend VALUES(?,?,?,?)').run('budget-test','test-owner',1000000,Date.now());
  await assert.rejects(call('kling'),/daily spending limit/);
  console.log('PASS Flash and Kling payloads, text-only routes, archive persistence, price reservation, missing key, reference limits, timeout duplicate prevention, rejected-charge release and daily budget');
}finally{globalThis.fetch=originalFetch;await unlink(temporary);}
