import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {libraryRoute,libraryJobs} from '../lab-worker/asset-library.mjs';
const db=new DatabaseSync(':memory:');
db.exec('CREATE TABLE jobs(id TEXT PRIMARY KEY,owner_id TEXT,created_at INTEGER,params TEXT)');
const prepare=(sql,args=[])=>({bind(...a){return prepare(sql,a)},async all(){return {results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)},async run(){return db.prepare(sql).run(...args)}});
const env={LAB_DB:{prepare,batch:async list=>{db.exec('BEGIN');try{const r=[];for(const s of list)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const deps={body:r=>r.json(),uid:v=>{if(typeof v!=='string'||!v)throw Error('bad id');return v},fail:(n,s)=>{throw Error(n+': '+s)},rows:async(e,s,...a)=>(await prepare(s,a).all()).results,first:(e,s,...a)=>prepare(s,a).first(),run:(e,s,...a)=>prepare(s,a).run(),jobView:j=>({id:j.id})};
const route=(owner,path,body)=>libraryRoute(new Request('https://lab.test'+path,{method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})}),env,owner,new URL('https://lab.test'+path),deps);
const query=(owner,qs='')=>libraryJobs(env,owner,new URL('https://lab.test?'+qs),deps);
for(let i=0;i<25;i++)db.prepare('INSERT INTO jobs VALUES(?,?,?,?)').run('a'+i,'alice',i+1,JSON.stringify({type:i%2?'image':'video'}));
db.prepare('INSERT INTO jobs VALUES(?,?,?,?)').run('b1','bob',100,JSON.stringify({type:'image'}));
const {folder}=await route('alice','/api/library/folders',{name:'Berlin 2063'});
await route('alice','/api/library/members',{folderId:folder.id,ids:['a0','a1']});
await route('alice','/api/library/members',{favorite:true,ids:['a1']});
assert.equal((await route('alice','/api/library')).folders[0].count,2);
assert.equal((await route('bob','/api/library')).folders.length,0);
assert.deepEqual((await query('alice','folder='+folder.id)).jobs.map(j=>j.id),['a1','a0']);
assert.deepEqual((await query('alice','favorite=1')).jobs,[{id:'a1',favorite:true}]);
assert.deepEqual((await query('bob','folder='+folder.id)).jobs,[]);
await assert.rejects(route('bob','/api/library/members',{folderId:folder.id,ids:['b1']}),/404/);
await assert.rejects(route('alice','/api/library/members',{favorite:true,ids:['b1']}),/404/);
const page1=await query('alice'),page2=await query('alice',new URLSearchParams(page1.next));assert.equal(page1.jobs.length,20);assert.equal(page2.jobs.length,5);assert.equal(new Set([...page1.jobs,...page2.jobs].map(j=>j.id)).size,25);
await route('alice','/api/library/members',{folderId:folder.id,ids:['a0'],remove:true});
assert.equal((await query('alice','folder='+folder.id)).jobs.length,1);
await route('alice','/api/library/members',{favorite:false,ids:['a1']});assert.equal((await query('alice','favorite=1')).jobs.length,0);
db.prepare('DELETE FROM jobs WHERE id=?').run('a1');assert.equal((await route('alice','/api/library')).folders[0].count,0);
console.log('PASS persistence, media folders, favorites, ownership isolation, pagination, removal, deleted-record cleanup');
