import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {libraryRoute,libraryJobs} from '../lab-worker/asset-library.mjs';
const db=new DatabaseSync(':memory:');
db.exec('CREATE TABLE jobs(id TEXT PRIMARY KEY,owner_id TEXT,created_at INTEGER,params TEXT)');
const prepare=(sql,args=[])=>({bind(...a){return prepare(sql,a)},async all(){return {results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)},async run(){return db.prepare(sql).run(...args)}});
const env={LAB_DB:{prepare,batch:async list=>{db.exec('BEGIN');try{const r=[];for(const s of list)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const deps={body:r=>r.json(),uid:v=>{if(typeof v!=='string'||!v)throw Error('bad id');return v},fail:(n,s)=>{throw Error(n+': '+s)},rows:async(e,s,...a)=>(await prepare(s,a).all()).results,first:(e,s,...a)=>prepare(s,a).first(),run:(e,s,...a)=>prepare(s,a).run(),jobView:j=>({id:j.id})};
const route=(owner,path,body)=>libraryRoute(new Request('https://lab.test'+path,{method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})}),env,owner,new URL('https://lab.test'+path),deps);
const query=(owner,qs='')=>libraryJobs(env,owner,new URL('https://lab.test?'+qs),deps);
for(let i=0;i<25;i++)db.prepare('INSERT INTO jobs VALUES(?,?,?,?)').run('a'+i,'alice',i+1,JSON.stringify({type:i%2?'image':'video'}));
db.prepare('INSERT INTO jobs VALUES(?,?,?,?)').run('b1','bob',100,JSON.stringify({type:'image'}));
const {folder}=await route('alice','/api/library/folders',{name:'Berlin 2063'});
await route('alice','/api/library/members',{folderId:folder.id,ids:['a0','a1']});
await route('alice','/api/library/members',{favorite:true,ids:['a1']});
assert.equal((await route('alice','/api/library')).folders[0].count,2);
assert.equal((await route('bob','/api/library')).folders.length,0);
assert.deepEqual((await query('alice','folder='+folder.id)).jobs.map(j=>j.id),['a1','a0']);
assert.deepEqual((await query('alice','favorite=1')).jobs,[{id:'a1',favorite:true}]);
assert.deepEqual((await query('bob','folder='+folder.id)).jobs,[]);
await assert.rejects(route('bob','/api/library/members',{folderId:folder.id,ids:['b1']}),/404/);
await assert.rejects(route('alice','/api/library/members',{favorite:true,ids:['b1']}),/404/);
const page1=await query('alice','unfiled=1'),page2=await query('alice',new URLSearchParams({...page1.next,unfiled:'1'}));assert.equal(page1.jobs.length,20);assert.equal(page2.jobs.length,3);assert.equal(new Set([...page1.jobs,...page2.jobs].map(j=>j.id)).size,23);
const all1=await query('alice'),all2=await query('alice',new URLSearchParams(all1.next));assert.equal(all1.jobs.length+all2.jobs.length,25,'All assets includes filed work');
assert.ok([...all1.jobs,...all2.jobs].some(j=>j.id==='a1'));
assert.ok([...page1.jobs,...page2.jobs].every(j=>!['a0','a1'].includes(j.id)));
for(const kind of ['image','video'])assert.ok((await query('alice','unfiled=1&kind='+kind)).jobs.every(j=>!['a0','a1'].includes(j.id)));
const {folder:second}=await route('alice','/api/library/folders',{name:'Second folder'});
await route('alice','/api/library/members',{folderId:second.id,ids:['a0']});
await route('alice','/api/library/members',{folderId:folder.id,ids:['a0'],remove:true});
assert.ok(!(await query('alice','unfiled=1&kind=video')).jobs.some(j=>j.id==='a0'),'Still archived while in another folder');
await route('alice','/api/library/members',{folderId:second.id,ids:['a0'],remove:true});
assert.ok((await query('alice','unfiled=1&kind=video')).jobs.some(j=>j.id==='a0'),'Returns to main grid after last folder membership removed');
assert.equal((await query('alice','folder='+folder.id)).jobs.length,1);
await route('alice','/api/library/members',{favorite:false,ids:['a1']});assert.equal((await query('alice','favorite=1')).jobs.length,0);
db.prepare('DELETE FROM jobs WHERE id=?').run('a1');assert.equal((await route('alice','/api/library')).folders[0].count,0);
console.log('PASS persistence, media folders, favorites, ownership isolation, pagination, removal, deleted-record cleanup');

await route('alice','/api/library/archive',{ids:['a2','a3']});
await route('alice','/api/library/archive',{ids:['a4']});
const archives=(await route('alice','/api/library')).folders.filter(f=>f.name==='Archive');
assert.equal(archives.length,1);assert.equal(archives[0].count,3);
assert.deepEqual((await query('alice','folder='+archives[0].id)).jobs.map(j=>j.id),['a4','a3','a2']);
assert.ok((await query('alice','unfiled=1')).jobs.every(j=>!['a2','a3','a4'].includes(j.id)));
assert.ok((await query('alice','kind=video')).jobs.some(j=>j.id==='a4'));
await assert.rejects(route('bob','/api/library/archive',{ids:['a2']}),/404/);
console.log('PASS dedicated Archive action, one Archive folder, account isolation and All assets retention');
