from pathlib import Path
root=Path('.')
f=root/'lab/index.html';s=f.read_text().replace('20260926-3','20260926-4')
s=s.replace('Still image. Moving possibility.','Image. Motion. Possibility.').replace('Your images, in motion.','Your private creative workspace.').replace('Your private motion studio.','Your private image and motion studio.')
s=s.replace('<div class="workspace">','<nav class="tool-switch" aria-label="Creative tool"><button id="tool-video" class="tool-tab active" type="button" aria-pressed="true">Video <small>Wan 3.0</small></button><button id="tool-image" class="tool-tab" type="button" aria-pressed="false">Image <small>Seedream 5.0 Pro</small></button></nav>\n<div class="workspace">')
s=s.replace('<span>01 / Image to Video</span><span class="engine-pill">WAN 3.0</span>', '<span id="mode-heading">01 / Image to Video</span><span class="engine-pill" id="engine-name">WAN 3.0</span>')
s=s.replace('<div class="mode-switch" role=', '<div id="video-modes" class="mode-switch" role=')
s=s.replace('<p class="fine compact-fine">Name each reference in the prompt, for example: Reference 1 = character, Reference 2 = outfit.</p>', '''<p class="fine compact-fine" id="reference-help">Reference numbers, filenames, roles and notes are added to your generation prompt. They guide the model; they do not guarantee identity matching.</p>
<div class="pack-bar"><label><span class="label">Reference packs</span><select id="pack-select"><option value="">Choose a saved pack</option></select></label><button id="pack-load" class="quiet" type="button">Load</button><button id="pack-save" class="quiet" type="button">Save pack</button><button id="pack-delete" class="quiet" type="button">Delete pack</button></div>''')
s=s.replace('class="label prompt-label" for="prompt"','class="label prompt-label" id="prompt-label" for="prompt"')
s=s.replace('<label><span class="label">Duration</span>', '<label id="duration-control"><span class="label">Duration</span>')
s=s.replace('<div class="utility-row">','<label id="format-control" hidden><span class="label">Image format</span><select id="output-format"><option value="jpeg">JPEG</option><option value="png">PNG</option></select></label>\n<div class="utility-row" id="video-utilities">')
s=s.replace('The Lab uses hosted Wan 3.0 image-to-video and reference-to-video endpoints. Your computer does not render the video.','Wan 3.0 handles video. Seedream 5.0 Pro handles images and reference-based edits. Your existing provider key is used for both; prices are quoted before payment. Your computer does not render the media.')
s=s.replace('Your source is shared with the provider to generate the video.', 'Your prompt and selected references are shared with the provider to generate the result.')
f.write_text(s)
f=root/'lab/lab.js';s=f.read_text()
s=s.replace("let resultUrl=null,", "let tool='video', packs=[],resultKind='video',resultExt='mp4';\nlet resultUrl=null,")
a=s.index('function settings()');b=s.index('async function api(',a)
s=s[:a]+'''function referenceRoles(){return references.map(r=>({name:r.file.name,role:r.role||'none',note:r.note||''}));}
function settings(){if(tool==='image')return {type:'image',mode:'image',prompt:$('prompt').value.trim(),resolution:$('resolution').value,aspectRatio:$('ratio').value,outputFormat:$('output-format').value,referenceRoles:referenceRoles()};return {type:'video',mode,prompt:$('prompt').value.trim(),duration:Number($('duration').value),resolution:$('resolution').value,aspectRatio:$('ratio').value,seed:$('seed').value,audio:$('audio').checked,referenceRoles:referenceRoles()};}
function hasInput(){return tool==='image'?!!$('prompt').value.trim():mode==='start'?!!file:references.length>0;}
function update(){const p=settings(),ratio=p.aspectRatio==='auto'?(mode==='reference'?'adaptive':'source ratio'):p.aspectRatio;$('settings-summary').textContent=tool==='image'?`Image / ${p.resolution.toUpperCase()} / ${ratio}`:`${p.duration}s / ${p.resolution} / ${ratio}`;$('save').disabled=!owner||!hasInput()||busy;$('clear').disabled=(!file&&!lastFile&&!references.length&&!resultUrl)||busy;$('generate').disabled=!owner||!hasInput()||!p.prompt||busy||!!activeJob;$('generate').textContent=config.enabled?'Review price & generate':'Connect generation provider';for(const el of document.querySelectorAll('.controls input,.controls select,.controls textarea,.mode-tab,.tool-tab'))el.disabled=busy;}
function options(id,values,value){$(id).replaceChildren(...values.map(v=>new Option(v==='auto'?'Follow reference':v.toUpperCase(),v)));$(id).value=value;}
function setTool(value){tool=value==='image'?'image':'video';const image=tool==='image';$('tool-image').classList.toggle('active',image);$('tool-video').classList.toggle('active',!image);$('tool-image').setAttribute('aria-pressed',String(image));$('tool-video').setAttribute('aria-pressed',String(!image));$('video-modes').hidden=image;$('duration-control').hidden=image;$('video-utilities').hidden=image;$('format-control').hidden=!image;$('start-mode').hidden=image||mode!=='start';$('reference-mode').hidden=!image&&mode!=='reference';$('mode-heading').textContent=image?'02 / Text to Image + Reference Edit':'01 / Image to Video';$('engine-name').textContent=image?'SEEDREAM 5.0 PRO':'WAN 3.0';$('prompt-label').textContent=image?'Image direction':'Motion direction';$('prompt').maxLength=image?5000:6000;$('prompt').placeholder=image?'Describe the image. Add references for identity, wardrobe, a room or an object, or start with text only.':'One clear action, one camera move, light, atmosphere and sound.';options('resolution',image?['1k','2k']:['480p','720p','1080p'],image?'2k':'1080p');options('ratio',image?['auto','1:1','4:3','3:4','16:9','9:16','3:2','2:3','4:5','5:4','21:9','9:21','2:1','1:2','3:1','1:3']:['auto','16:9','9:16','1:1','4:3','3:4'],image?'1:1':'auto');clearResult();resetPreview();update();}
$('tool-image').onclick=()=>{if(!busy)setTool('image');};$('tool-video').onclick=()=>{if(!busy)setTool('video');};
''' + s[b:]
s=s.replace("const item=mode==='start'?", "const item=tool==='video'&&mode==='start'?")
s=s.replace("async function setLastImage(candidate,id=null){const item=await inspectImage(candidate);release(lastUrl);", "async function setLastImage(candidate,id=null){const e=epoch,item=await inspectImage(candidate);if(e!==epoch||!owner){release(item.url);return false;}release(lastUrl);")
a=s.index('function renderReferences()');b=s.index('async function addReferences(',a)
s=s[:a]+'''function renderReferences(){const box=$('reference-list');box.replaceChildren();references.forEach((r,i)=>{const item=document.createElement('div');item.className='reference-item';const img=document.createElement('img');img.src=r.url;img.alt='Reference '+(i+1);const fields=document.createElement('div');fields.className='reference-fields';const title=document.createElement('strong');title.textContent='Reference '+(i+1)+' / '+r.file.name;const role=document.createElement('select');role.setAttribute('aria-label','Role for reference '+(i+1));for(const name of ['none','identity','outfit','room','pose','object','style','lighting','custom'])role.add(new Option(name==='none'?'No assigned role':name,name));role.value=r.role||'none';role.onchange=()=>{r.role=role.value;};const note=document.createElement('input');note.type='text';note.maxLength=300;note.placeholder='Use only the outfit, keep the room…';note.setAttribute('aria-label','Note for reference '+(i+1));note.value=r.note||'';note.oninput=()=>{r.note=note.value;};fields.append(title,role,note);const controls=document.createElement('div');controls.className='reference-actions';const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.onclick=()=>{if(busy)return;release(r.url);references.splice(i,1);renderReferences();resetPreview();update();};const up=document.createElement('button');up.type='button';up.textContent='Up';up.disabled=i===0;up.onclick=()=>{if(busy||i===0)return;[references[i-1],references[i]]=[references[i],references[i-1]];renderReferences();resetPreview();update();};controls.append(up,remove);item.append(img,fields,controls);box.append(item);});$('ref-count').textContent=`${references.length} / 10`;}
''' + s[b:]
s=s.replace("async function addReferences(list,ids=[]){const incoming=[...list];", "async function addReferences(list,ids=[],labels=[]){const e=epoch,incoming=[...list];")
s=s.replace("const item=await inspectImage(incoming[i]);item.id=ids[i]||null;references.push(item);", "const item=await inspectImage(incoming[i]);if(e!==epoch||!owner){release(item.url);return;}item.id=ids[i]||null;item.role=labels[i]?.role||'none';item.note=labels[i]?.note||'';references.push(item);")
s=s.replace("async function ensureInputs(){if(mode==='reference')", "async function ensureInputs(){if(tool==='image'&&!references.length)return {sourceId:null,lastSourceId:null,referenceSourceIds:[]};if(tool==='image'||mode==='reference')")
s=s.replace("'Wan 3.0 / SpicyAPI connected · Live quotes before payment'", "'SpicyAPI connected / Video + Image · Live quotes before payment'")
s=s.replace("const modeName=q.settings.mode==='reference'?'Reference to Video':'Image to Video';$('quote-settings').textContent=`Wan 3.0 / ${modeName} / ${q.settings.duration}s / ${q.settings.resolution}`;", "const isImage=q.settings.type==='image',modeName=q.settings.mode==='reference'?'Reference to Video':'Image to Video';$('quote-settings').textContent=isImage?`Seedream 5.0 Pro / ${q.settings.referenceSourceIds.length?'Reference Edit':'Text to Image'} / ${q.settings.resolution.toUpperCase()} / ${q.settings.aspectRatio}`:`Wan 3.0 / ${modeName} / ${q.settings.duration}s / ${q.settings.resolution}`;")
s=s.replace('Generating your video…','Generating your result…').replace('Saving the finished video to your private archive.','Saving the finished result to your private archive.').replace('Video saved. Open it from history.','Result saved. Open it from history.')
a=s.index('async function restore(');b=s.index('const observer=',a)
s=s[:a]+'''async function restore(job){clearMedia();const p=job.settings||{};setTool(p.type||'video');setMode(p.mode||'start');if(tool==='image'){$('start-mode').hidden=true;$('reference-mode').hidden=false;}const refs=tool==='image'||p.mode==='reference';if(refs){const ids=p.referenceSourceIds||[];const files=await Promise.all(ids.map((id,i)=>assetFile(id,(p.referenceRoles?.[i]?.name||'reference-'+(i+1)).replace(/\\.[^.]+$/,''))));await addReferences(files,ids,p.referenceRoles||[]);}else if(job.sourceId){await setImage(await assetFile(job.sourceId,'start-frame'),job.sourceId);if(p.lastSourceId)await setLastImage(await assetFile(p.lastSourceId,'last-frame'),p.lastSourceId);}$('prompt').value=p.prompt||'';
  if(p.duration&&!([...$('duration').options].some(o=>Number(o.value)===p.duration)))$('duration').add(new Option(p.duration+' sec',String(p.duration)));
  $('duration').value=p.duration||15;$('resolution').value=p.resolution||(tool==='image'?'2k':'1080p');$('ratio').value=p.aspectRatio||'auto';$('seed').value=p.seed??'';$('audio').checked=p.audio!==false;$('output-format').value=p.outputFormat||'jpeg';update();notify('Original media, reference roles, prompt and settings restored. Nothing generated or charged.');$('prompt').focus();window.scrollTo({top:0,behavior:'smooth'});}
async function openVideo(job){const blob=await api('/api/assets/'+job.outputId,{blob:true});clearResult();resultUrl=URL.createObjectURL(blob);resultId=job.outputId;resultKind=blob.type.startsWith('image/')?'image':'video';resultExt=resultKind==='video'?'mp4':blob.type==='image/jpeg'?'jpg':blob.type.split('/')[1];if(resultKind==='image'){$('preview').src=resultUrl;$('preview').hidden=false;$('video').hidden=true;}else{$('video').src=resultUrl;$('video').hidden=false;$('preview').hidden=true;}$('empty').hidden=true;$('download').hidden=false;$('download').textContent='Download '+resultExt.toUpperCase();$('preview-label').textContent='Result / '+(resultKind==='image'?'Image':job.settings.duration+'s');document.querySelector('.stage').scrollIntoView({behavior:'smooth',block:'center'});}
function downloadResult(){if(!resultUrl)return;const a=document.createElement('a');a.href=resultUrl;a.download='parallel-vision-'+resultId+'.'+resultExt;document.body.append(a);a.click();a.remove();}
$('download').onclick=downloadResult;
async function animateImage(job){clearMedia();setTool('video');setMode('start');await setImage(await assetFile(job.outputId,'generated-image'),job.outputId);$('prompt').value='';update();notify('Generated image loaded as the video start frame. Add motion direction and review the price.');window.scrollTo({top:0,behavior:'smooth'});}
async function loadPacks(){const data=await api('/api/packs');packs=data.packs;$('pack-select').replaceChildren(new Option('Choose a saved pack',''),...packs.map(p=>new Option(p.name,p.id)));}
$('pack-save').onclick=()=>action(async()=>{if(!references.length)throw new Error('Add reference images first.');const name=window.prompt('Name this reference pack, for example Nina FOK / Editorial');if(!name?.trim())return;const ids=await ensureReferences();await api('/api/packs',{method:'POST',body:{name:name.trim(),referenceSourceIds:ids,referenceRoles:referenceRoles()}});await loadPacks();notify('Reference pack saved privately. No generation charge.');});
$('pack-load').onclick=()=>action(async()=>{const pack=packs.find(p=>p.id===$('pack-select').value);if(!pack)throw new Error('Choose a saved pack.');if(references.length&&!confirm('Replace the current references with this pack?'))return;const files=await Promise.all(pack.refs.map(r=>assetFile(r.id,r.name.replace(/\\.[^.]+$/,''))));references.forEach(r=>release(r.url));references=[];await addReferences(files,pack.refs.map(r=>r.id),pack.refs);notify('Pack loaded with reference order, roles and notes.');});
$('pack-delete').onclick=()=>action(async()=>{const id=$('pack-select').value;if(!id||!confirm('Delete this reference pack? Existing generation history remains.'))return;await api('/api/packs/'+id,{method:'DELETE'});await loadPacks();notify('Reference pack deleted.');});
''' + s[b:]
s=s.replace("img.dataset.asset=j.sourceId;", "if(j.settings.type==='image'&&j.outputId)img.dataset.asset=j.outputId;else if(j.sourceId)img.dataset.asset=j.sourceId;")
s=s.replace("meta.textContent=`${j.status.toUpperCase()} / ${j.settings.duration}s / ${j.settings.resolution} / ${new Date(j.createdAt).toLocaleDateString()}`;", "meta.textContent=`${j.status.toUpperCase()} / ${j.settings.type==='image'?'IMAGE':j.settings.duration+'s'} / ${j.settings.resolution} / ${new Date(j.createdAt).toLocaleDateString()}`;")
s=s.replace("if(j.outputId)actions.append(button('View video',()=>openVideo(j)));", "if(j.outputId){actions.append(button(j.settings.type==='image'?'View image':'View video',()=>openVideo(j)));actions.append(button('Download',async()=>{await openVideo(j);downloadResult();}));if(j.settings.type==='image')actions.append(button('Use in Video',()=>animateImage(j)));}")
s=s.replace("observer.observe(img);", "if(img.dataset.asset)observer.observe(img);else{img.hidden=true;}")
s=s.replace("await loadHistory();}catch(e){lock();", "await loadHistory();await loadPacks();}catch(e){lock();")
s=s.replace("currentQuote=null;config={};}", "currentQuote=null;config={};packs=[];$('pack-select').replaceChildren(new Option('Choose a saved pack',''));}")
s=s.replace("['prompt','duration','resolution','ratio','seed','audio']", "['prompt','duration','resolution','ratio','seed','audio','output-format']")
f.write_text(s)
f=root/'lab/lab.css';s=f.read_text()+'''
/* Private image/video workbench additions, isolated from the public site. */
.tool-switch{display:flex;gap:12px;margin:22px 0}.tool-tab{display:flex;align-items:center;gap:16px;border:1px solid #41423d;padding:14px 20px;background:transparent;color:inherit;cursor:pointer;font-size:15px}.tool-tab small{font-size:10px;letter-spacing:.08em;opacity:.6}.tool-tab.active{background:#dddcd4;color:#111210;border-color:#dddcd4}.reference-list{display:flex;flex-direction:column;gap:12px}.reference-item{display:grid;grid-template-columns:68px minmax(0,1fr) auto;gap:12px;align-items:start;padding:10px;border:1px solid #363730;position:relative;aspect-ratio:auto;overflow:visible}.reference-item>img{width:68px;height:82px;object-fit:cover}.reference-fields{min-width:0;display:grid;gap:7px}.reference-fields strong{font-size:10px;overflow-wrap:anywhere;line-height:1.4}.reference-fields input,.reference-fields select{width:100%;padding:7px;font-size:11px}.reference-actions{display:grid;gap:8px}.reference-item .reference-actions button{position:static;inset:auto;width:auto;height:auto;border:0;background:transparent;color:inherit;font-size:10px;padding:4px;cursor:pointer}.pack-bar{display:flex;flex-wrap:wrap;align-items:end;gap:8px;margin:14px 0}.pack-bar label{flex:1 1 180px;min-width:0}.pack-bar button{font-size:10px}.pack-bar select{width:100%}#format-control{display:block;margin:14px 0}#format-control[hidden],[hidden]{display:none!important}@media(max-width:540px){.tool-tab{flex:1;justify-content:space-between;padding:12px}.tool-tab small{font-size:8px}.reference-item{grid-template-columns:52px minmax(0,1fr);gap:8px}.reference-item>img{width:52px;height:68px}.reference-actions{grid-column:2;display:flex}.tool-switch{gap:8px}}
'''
f.write_text(s)
