// Presets are assembled on the backend; clients send only the preset ID.
export const SOUL_PRESETS=Object.freeze([
  {id:'photographic-real-skin',label:'Photographic / Real Skin',imageFidelity:.82,description:'Neutral photograph, natural skin texture.',direction:'Neutral photographic realism, visible pores, fine skin texture, subtle imperfections, natural fine body hair, believable skin folds, realistic eyes and individual hairs, natural tonal transitions, restrained retouching.'},
  {id:'editorial-fashion',label:'Editorial Fashion',imageFidelity:.76,description:'Refined fashion photography with natural skin.',direction:'Refined European fashion editorial, deliberate framing, realistic fabric and wardrobe detail, controlled light, moderate contrast, subtle magazine finish, natural skin.'},
  {id:'flash-editorial',label:'Flash Editorial',imageFidelity:.80,description:'Direct flash, tactile skin and candid detail.',direction:'On-camera direct flash, crisp flash shadows, realistic specular highlights, visible skin texture, candid backstage fashion photograph, slight 35mm snapshot imperfection.'},
  {id:'moody-neon-cinema',label:'Moody Neon Cinema',imageFidelity:.68,description:'Nocturnal colour, practical lights and halation.',direction:'Romantic nocturnal photograph, mixed tungsten and neon practical light, deep red and amber with restrained green or cyan accents, low-key exposure, soft halation and atmospheric falloff, realistic skin, analogue film colour.'},
  {id:'soft-intimate',label:'Soft Intimate',imageFidelity:.80,description:'Warm tones and soft natural light.',direction:'Soft window or practical lamp light, warm natural skin, gentle shadows, low contrast, visible skin microtexture, natural lens rendering, quiet intimate photographic atmosphere.'},
  {id:'night-hotel',label:'Night Hotel',imageFidelity:.74,description:'Warm pools of light and dark room falloff.',direction:'Late-night hotel photographic mood, warm bedside practical lamps, dark room falloff, deep shadows, tactile sheets and fabric, elegant believable European editorial finish.'},
  {id:'dirty-analog',label:'Dirty Analog',imageFidelity:.76,description:'35mm texture and imperfect exposure.',direction:'35mm film grain, subtle colour cast, imperfect exposure, slight lens softness, flash and ambient light mismatch, tactile photographic realism.'},
  {id:'studio-clean',label:'Studio Clean',imageFidelity:.78,description:'Controlled light and neutral colour.',direction:'Controlled studio photographic light, neutral colour, accurate natural skin, coherent anatomy, precise facial detail, low stylization. Retain the source environment unless a change is requested.'}
].map(p=>Object.freeze({...p,identityStrength:1})));
export const publicSoulPresets=()=>SOUL_PRESETS.map(({direction,...p})=>p);
export const soulPreset=id=>SOUL_PRESETS.find(p=>p.id===id);
